[colors.primary]
background = "#141f1f"
foreground = "#fbeab6"
dim_foreground = "#dbc170"
bright_foreground = "#fbeab6"

[colors.cursor]
text = "#141f1f"
cursor = "#fbeab6"

[colors.vi_mode_cursor]
text = "#141f1f"
cursor = "#fbeab6"

[colors.search.matches]
foreground = "#141f1f"
background = "#507c7c"

[colors.search.focused_match]
foreground = "#141f1f"
background = "#66e591"

[colors.footer_bar]
foreground = "#141f1f"
background = "#507c7c"

[colors.hints.start]
foreground = "#141f1f"
background = "#92b9b9"

[colors.hints.end]
foreground = "#141f1f"
background = "#507c7c"

[colors.selection]
text = "#141f1f"
background = "#3c5d5d"

[colors.normal]
black = "#283e3e"
red = "#eb9393"
green = "#66e591"
yellow = "#92b9b9"
blue = "#9393eb"
magenta = "#eb93eb"
cyan = "#51bde1"
white = "#fbeab6"

[colors.bright]
black = "#283e3e"
red = "#eb9393"
green = "#66e591"
yellow = "#92b9b9"
blue = "#9393eb"
magenta = "#eb93eb"
cyan = "#51bde1"
white = "#fbeab6"

[colors.dim]
black = "#283e3e"
red = "#eb9393"
green = "#66e591"
yellow = "#92b9b9"
blue = "#9393eb"
magenta = "#eb93eb"
cyan = "#51bde1"
white = "#fbeab6"