[colors.primary]
background = "#161d16"
foreground = "#c5d3c5"
dim_foreground = "#8ba78b"
bright_foreground = "#c5d3c5"

[colors.cursor]
text = "#161d16"
cursor = "#c5d3c5"

[colors.vi_mode_cursor]
text = "#161d16"
cursor = "#c5d3c5"

[colors.search.matches]
foreground = "#161d16"
background = "#587458"

[colors.search.focused_match]
foreground = "#161d16"
background = "#b3f471"

[colors.footer_bar]
foreground = "#161d16"
background = "#587458"

[colors.hints.start]
foreground = "#161d16"
background = "#f4f471"

[colors.hints.end]
foreground = "#161d16"
background = "#587458"

[colors.selection]
text = "#161d16"
background = "#425742"

[colors.normal]
black = "#2c3a2c"
red = "#f49271"
green = "#b3f471"
yellow = "#f4f471"
blue = "#71f4f4"
magenta = "#f688a4"
cyan = "#71f4b3"
white = "#c5d3c5"

[colors.bright]
black = "#2c3a2c"
red = "#f49271"
green = "#b3f471"
yellow = "#f4f471"
blue = "#71f4f4"
magenta = "#f688a4"
cyan = "#71f4b3"
white = "#c5d3c5"

[colors.dim]
black = "#2c3a2c"
red = "#f49271"
green = "#b3f471"
yellow = "#f4f471"
blue = "#71f4f4"
magenta = "#f688a4"
cyan = "#71f4b3"
white = "#c5d3c5"