[colors.primary]
background = "#d4d4dd"
foreground = "#3e310f"
dim_foreground = "#7d6a36"
bright_foreground = "#3e310f"

[colors.cursor]
text = "#d4d4dd"
cursor = "#3e310f"

[colors.vi_mode_cursor]
text = "#d4d4dd"
cursor = "#3e310f"

[colors.search.matches]
foreground = "#d4d4dd"
background = "#af9b6a"

[colors.search.focused_match]
foreground = "#d4d4dd"
background = "#3a785b"

[colors.footer_bar]
foreground = "#d4d4dd"
background = "#af9b6a"

[colors.hints.start]
foreground = "#d4d4dd"
background = "#595959"

[colors.hints.end]
foreground = "#d4d4dd"
background = "#af9b6a"

[colors.selection]
text = "#d4d4dd"
background = "#c1b18b"

[colors.normal]
black = "#b8b8c6"
red = "#862d2d"
green = "#3a785b"
yellow = "#595959"
blue = "#3a3a78"
magenta = "#862d43"
cyan = "#365a7d"
white = "#3e310f"

[colors.bright]
black = "#b8b8c6"
red = "#862d2d"
green = "#3a785b"
yellow = "#595959"
blue = "#3a3a78"
magenta = "#862d43"
cyan = "#365a7d"
white = "#3e310f"

[colors.dim]
black = "#b8b8c6"
red = "#862d2d"
green = "#3a785b"
yellow = "#595959"
blue = "#3a3a78"
magenta = "#862d43"
cyan = "#365a7d"
white = "#3e310f"