[colors.primary]
background = "#22222a"
foreground = "#f0e4c2"
dim_foreground = "#c9b682"
bright_foreground = "#f0e4c2"

[colors.cursor]
text = "#22222a"
cursor = "#f0e4c2"

[colors.vi_mode_cursor]
text = "#22222a"
cursor = "#f0e4c2"

[colors.search.matches]
foreground = "#22222a"
background = "#958250"

[colors.search.focused_match]
foreground = "#22222a"
background = "#a9d6c1"

[colors.footer_bar]
foreground = "#22222a"
background = "#958250"

[colors.hints.start]
foreground = "#22222a"
background = "#a6a6a6"

[colors.hints.end]
foreground = "#22222a"
background = "#958250"

[colors.selection]
text = "#22222a"
background = "#74653e"

[colors.normal]
black = "#393947"
red = "#d98c8c"
green = "#a9d6c1"
yellow = "#a6a6a6"
blue = "#9898cd"
magenta = "#d98c9f"
cyan = "#94b4d1"
white = "#f0e4c2"

[colors.bright]
black = "#393947"
red = "#d98c8c"
green = "#a9d6c1"
yellow = "#a6a6a6"
blue = "#9898cd"
magenta = "#d98c9f"
cyan = "#94b4d1"
white = "#f0e4c2"

[colors.dim]
black = "#393947"
red = "#d98c8c"
green = "#a9d6c1"
yellow = "#a6a6a6"
blue = "#9898cd"
magenta = "#d98c9f"
cyan = "#94b4d1"
white = "#f0e4c2"