[colors.primary]
background = "#d7d9db"
foreground = "#41140b"
dim_foreground = "#863a2d"
bright_foreground = "#41140b"

[colors.cursor]
text = "#d7d9db"
cursor = "#41140b"

[colors.vi_mode_cursor]
text = "#d7d9db"
cursor = "#41140b"

[colors.search.matches]
foreground = "#d7d9db"
background = "#ba6b5e"

[colors.search.focused_match]
foreground = "#d7d9db"
background = "#1b983a"

[colors.footer_bar]
foreground = "#d7d9db"
background = "#ba6b5e"

[colors.hints.start]
foreground = "#d7d9db"
background = "#93761f"

[colors.hints.end]
foreground = "#d7d9db"
background = "#ba6b5e"

[colors.selection]
text = "#d7d9db"
background = "#c98c82"

[colors.normal]
black = "#bcbfc2"
red = "#8e2525"
green = "#1b983a"
yellow = "#93761f"
blue = "#1b5998"
magenta = "#25258e"
cyan = "#248f8f"
white = "#41140b"

[colors.bright]
black = "#bcbfc2"
red = "#8e2525"
green = "#1b983a"
yellow = "#93761f"
blue = "#1b5998"
magenta = "#25258e"
cyan = "#248f8f"
white = "#41140b"

[colors.dim]
black = "#bcbfc2"
red = "#8e2525"
green = "#1b983a"
yellow = "#93761f"
blue = "#1b5998"
magenta = "#25258e"
cyan = "#248f8f"
white = "#41140b"