[colors.primary]
background = "#333036"
foreground = "#e6e4e7"
dim_foreground = "#b3aeb7"
bright_foreground = "#e6e4e7"

[colors.cursor]
text = "#333036"
cursor = "#e6e4e7"

[colors.vi_mode_cursor]
text = "#333036"
cursor = "#e6e4e7"

[colors.search.matches]
foreground = "#333036"
background = "#817887"

[colors.search.focused_match]
foreground = "#333036"
background = "#66cc7f"

[colors.footer_bar]
foreground = "#333036"
background = "#817887"

[colors.hints.start]
foreground = "#333036"
background = "#c0cc66"

[colors.hints.end]
foreground = "#333036"
background = "#817887"

[colors.selection]
text = "#333036"
background = "#67606c"

[colors.normal]
black = "#4d4851"
red = "#d66e5c"
green = "#66cc7f"
yellow = "#c0cc66"
blue = "#66b3cc"
magenta = "#cc6687"
cyan = "#66ccb3"
white = "#e6e4e7"

[colors.bright]
black = "#4d4851"
red = "#d66e5c"
green = "#66cc7f"
yellow = "#c0cc66"
blue = "#66b3cc"
magenta = "#cc6687"
cyan = "#66ccb3"
white = "#e6e4e7"

[colors.dim]
black = "#4d4851"
red = "#d66e5c"
green = "#66cc7f"
yellow = "#c0cc66"
blue = "#66b3cc"
magenta = "#cc6687"
cyan = "#66ccb3"
white = "#e6e4e7"