[colors.primary]
background = "#2e4242"
foreground = "#cbe0e7"
dim_foreground = "#b4c5cb"
bright_foreground = "#cbe0e7"

[colors.cursor]
text = "#2e4242"
cursor = "#cbe0e7"

[colors.vi_mode_cursor]
text = "#2e4242"
cursor = "#cbe0e7"

[colors.search.matches]
foreground = "#2e4242"
background = "#78a1a1"

[colors.search.focused_match]
foreground = "#2e4242"
background = "#a8f0a8"

[colors.footer_bar]
foreground = "#2e4242"
background = "#78a1a1"

[colors.hints.start]
foreground = "#2e4242"
background = "#def0a8"

[colors.hints.end]
foreground = "#2e4242"
background = "#78a1a1"

[colors.selection]
text = "#2e4242"
background = "#5e8787"

[colors.normal]
black = "#496969"
red = "#f0a8ba"
green = "#a8f0a8"
yellow = "#def0a8"
blue = "#a8f0f0"
magenta = "#baa8f0"
cyan = "#a8f0cc"
white = "#cbe0e7"

[colors.bright]
black = "#496969"
red = "#f0a8ba"
green = "#a8f0a8"
yellow = "#def0a8"
blue = "#a8f0f0"
magenta = "#baa8f0"
cyan = "#a8f0cc"
white = "#cbe0e7"

[colors.dim]
black = "#496969"
red = "#f0a8ba"
green = "#a8f0a8"
yellow = "#def0a8"
blue = "#a8f0f0"
magenta = "#baa8f0"
cyan = "#a8f0cc"
white = "#cbe0e7"