[colors.primary]
background = "#3b322b"
foreground = "#eae5e1"
dim_foreground = "#c9beb5"
bright_foreground = "#eae5e1"

[colors.cursor]
text = "#3b322b"
cursor = "#eae5e1"

[colors.vi_mode_cursor]
text = "#3b322b"
cursor = "#eae5e1"

[colors.search.matches]
foreground = "#3b322b"
background = "#947d6b"

[colors.search.focused_match]
foreground = "#3b322b"
background = "#99b34d"

[colors.footer_bar]
foreground = "#3b322b"
background = "#947d6b"

[colors.hints.start]
foreground = "#3b322b"
background = "#b3804d"

[colors.hints.end]
foreground = "#3b322b"
background = "#947d6b"

[colors.selection]
text = "#3b322b"
background = "#766456"

[colors.normal]
black = "#594b40"
red = "#ac5353"
green = "#99b34d"
yellow = "#b3804d"
blue = "#53ac96"
magenta = "#ac5380"
cyan = "#4db366"
white = "#eae5e1"

[colors.bright]
black = "#594b40"
red = "#ac5353"
green = "#99b34d"
yellow = "#b3804d"
blue = "#53ac96"
magenta = "#ac5380"
cyan = "#4db366"
white = "#eae5e1"

[colors.dim]
black = "#594b40"
red = "#ac5353"
green = "#99b34d"
yellow = "#b3804d"
blue = "#53ac96"
magenta = "#ac5380"
cyan = "#4db366"
white = "#eae5e1"