[colors.primary]
background = "#321b1b"
foreground = "#d5ddd9"
dim_foreground = "#9dafa7"
bright_foreground = "#d5ddd9"

[colors.cursor]
text = "#321b1b"
cursor = "#d5ddd9"

[colors.vi_mode_cursor]
text = "#321b1b"
cursor = "#d5ddd9"

[colors.search.matches]
foreground = "#321b1b"
background = "#677e74"

[colors.search.focused_match]
foreground = "#321b1b"
background = "#75d78d"

[colors.footer_bar]
foreground = "#321b1b"
background = "#677e74"

[colors.hints.start]
foreground = "#321b1b"
background = "#e4c567"

[colors.hints.end]
foreground = "#321b1b"
background = "#677e74"

[colors.selection]
text = "#321b1b"
background = "#50625a"

[colors.normal]
black = "#532d2d"
red = "#e46767"
green = "#75d78d"
yellow = "#e4c567"
blue = "#75a6d7"
magenta = "#d775a6"
cyan = "#75d7d7"
white = "#d5ddd9"

[colors.bright]
black = "#532d2d"
red = "#e46767"
green = "#75d78d"
yellow = "#e4c567"
blue = "#75a6d7"
magenta = "#d775a6"
cyan = "#75d7d7"
white = "#d5ddd9"

[colors.dim]
black = "#532d2d"
red = "#e46767"
green = "#75d78d"
yellow = "#e4c567"
blue = "#75a6d7"
magenta = "#d775a6"
cyan = "#75d7d7"
white = "#d5ddd9"