[colors.primary]
background = "#3a3d34"
foreground = "#b4e2ee"
dim_foreground = "#abbfc4"
bright_foreground = "#b4e2ee"

[colors.cursor]
text = "#3a3d34"
cursor = "#b4e2ee"

[colors.vi_mode_cursor]
text = "#3a3d34"
cursor = "#b4e2ee"

[colors.search.matches]
foreground = "#3a3d34"
background = "#6f919b"

[colors.search.focused_match]
foreground = "#3a3d34"
background = "#8cd9b3"

[colors.footer_bar]
foreground = "#3a3d34"
background = "#6f919b"

[colors.hints.start]
foreground = "#3a3d34"
background = "#c8dd88"

[colors.hints.end]
foreground = "#3a3d34"
background = "#6f919b"

[colors.selection]
text = "#3a3d34"
background = "#58767e"

[colors.normal]
black = "#55584b"
red = "#dd889d"
green = "#8cd9b3"
yellow = "#c8dd88"
blue = "#8c9fd9"
magenta = "#d98cc6"
cyan = "#8cc6d9"
white = "#b4e2ee"

[colors.bright]
black = "#55584b"
red = "#dd889d"
green = "#8cd9b3"
yellow = "#c8dd88"
blue = "#8c9fd9"
magenta = "#d98cc6"
cyan = "#8cc6d9"
white = "#b4e2ee"

[colors.dim]
black = "#55584b"
red = "#dd889d"
green = "#8cd9b3"
yellow = "#c8dd88"
blue = "#8c9fd9"
magenta = "#d98cc6"
cyan = "#8cc6d9"
white = "#b4e2ee"