[colors.primary]
background = "#3a3d34"
foreground = "#b4e2ee"
dim_foreground = "#abbfc4"
bright_foreground = "#b4e2ee"

[colors.cursor]
text = "#3a3d34"
cursor = "#b4e2ee"

[colors.vi_mode_cursor]
text = "#3a3d34"
cursor = "#b4e2ee"

[colors.search.matches]
foreground = "#3a3d34"
background = "#6f919b"

[colors.search.focused_match]
foreground = "#3a3d34"
background = "#9ddd88"

[colors.footer_bar]
foreground = "#3a3d34"
background = "#6f919b"

[colors.hints.start]
foreground = "#3a3d34"
background = "#dddd88"

[colors.hints.end]
foreground = "#3a3d34"
background = "#6f919b"

[colors.selection]
text = "#3a3d34"
background = "#58767e"

[colors.normal]
black = "#55584b"
red = "#dd889d"
green = "#9ddd88"
yellow = "#dddd88"
blue = "#88b3dd"
magenta = "#d98cc6"
cyan = "#88ddc8"
white = "#b4e2ee"

[colors.bright]
black = "#55584b"
red = "#dd889d"
green = "#9ddd88"
yellow = "#dddd88"
blue = "#88b3dd"
magenta = "#d98cc6"
cyan = "#88ddc8"
white = "#b4e2ee"

[colors.dim]
black = "#55584b"
red = "#dd889d"
green = "#9ddd88"
yellow = "#dddd88"
blue = "#88b3dd"
magenta = "#d98cc6"
cyan = "#88ddc8"
white = "#b4e2ee"