[colors.primary]
background = "#2e3142"
foreground = "#e1c1e1"
dim_foreground = "#c4abc4"
bright_foreground = "#e1c1e1"

[colors.cursor]
text = "#2e3142"
cursor = "#e1c1e1"

[colors.vi_mode_cursor]
text = "#2e3142"
cursor = "#e1c1e1"

[colors.search.matches]
foreground = "#2e3142"
background = "#9b6f9b"

[colors.search.focused_match]
foreground = "#2e3142"
background = "#bed775"

[colors.footer_bar]
foreground = "#2e3142"
background = "#9b6f9b"

[colors.hints.start]
foreground = "#2e3142"
background = "#eccf79"

[colors.hints.end]
foreground = "#2e3142"
background = "#9b6f9b"

[colors.selection]
text = "#2e3142"
background = "#7e587e"

[colors.normal]
black = "#434860"
red = "#e06c6c"
green = "#bed775"
yellow = "#eccf79"
blue = "#79d2d2"
magenta = "#d874a6"
cyan = "#74d88d"
white = "#e1c1e1"

[colors.bright]
black = "#434860"
red = "#e06c6c"
green = "#bed775"
yellow = "#eccf79"
blue = "#79d2d2"
magenta = "#d874a6"
cyan = "#74d88d"
white = "#e1c1e1"

[colors.dim]
black = "#434860"
red = "#e06c6c"
green = "#bed775"
yellow = "#eccf79"
blue = "#79d2d2"
magenta = "#d874a6"
cyan = "#74d88d"
white = "#e1c1e1"