[colors.primary]
background = "#121721"
foreground = "#dbbddb"
dim_foreground = "#b87ab8"
bright_foreground = "#dbbddb"

[colors.cursor]
text = "#121721"
cursor = "#dbbddb"

[colors.vi_mode_cursor]
text = "#121721"
cursor = "#dbbddb"

[colors.search.matches]
foreground = "#121721"
background = "#7a527a"

[colors.search.focused_match]
foreground = "#121721"
background = "#7de898"

[colors.footer_bar]
foreground = "#121721"
background = "#7a527a"

[colors.hints.start]
foreground = "#121721"
background = "#e8dc7d"

[colors.hints.end]
foreground = "#121721"
background = "#7a527a"

[colors.selection]
text = "#121721"
background = "#5c3d5c"

[colors.normal]
black = "#242e42"
red = "#e87d98"
green = "#7de898"
yellow = "#e8dc7d"
blue = "#8cc6d9"
magenta = "#d98cd9"
cyan = "#7de8cd"
white = "#dbbddb"

[colors.bright]
black = "#242e42"
red = "#e87d98"
green = "#7de898"
yellow = "#e8dc7d"
blue = "#8cc6d9"
magenta = "#d98cd9"
cyan = "#7de8cd"
white = "#dbbddb"

[colors.dim]
black = "#242e42"
red = "#e87d98"
green = "#7de898"
yellow = "#e8dc7d"
blue = "#8cc6d9"
magenta = "#d98cd9"
cyan = "#7de8cd"
white = "#dbbddb"