[colors.primary]
background = "#121721"
foreground = "#ebadeb"
dim_foreground = "#c270c2"
bright_foreground = "#ebadeb"

[colors.cursor]
text = "#121721"
cursor = "#ebadeb"

[colors.vi_mode_cursor]
text = "#121721"
cursor = "#ebadeb"

[colors.search.matches]
foreground = "#121721"
background = "#844884"

[colors.search.focused_match]
foreground = "#121721"
background = "#7de8cd"

[colors.footer_bar]
foreground = "#121721"
background = "#844884"

[colors.hints.start]
foreground = "#121721"
background = "#7dcde8"

[colors.hints.end]
foreground = "#121721"
background = "#844884"

[colors.selection]
text = "#121721"
background = "#633663"

[colors.normal]
black = "#242e42"
red = "#b37de8"
green = "#7de8cd"
yellow = "#7dcde8"
blue = "#e87de8"
magenta = "#7d7de8"
cyan = "#e87db3"
white = "#ebadeb"

[colors.bright]
black = "#242e42"
red = "#b37de8"
green = "#7de8cd"
yellow = "#7dcde8"
blue = "#e87de8"
magenta = "#7d7de8"
cyan = "#e87db3"
white = "#ebadeb"

[colors.dim]
black = "#242e42"
red = "#b37de8"
green = "#7de8cd"
yellow = "#7dcde8"
blue = "#e87de8"
magenta = "#7d7de8"
cyan = "#e87db3"
white = "#ebadeb"