[colors.primary]
background = "#2e3142"
foreground = "#eeb5ee"
dim_foreground = "#c4abc4"
bright_foreground = "#eeb5ee"

[colors.cursor]
text = "#2e3142"
cursor = "#eeb5ee"

[colors.vi_mode_cursor]
text = "#2e3142"
cursor = "#eeb5ee"

[colors.search.matches]
foreground = "#2e3142"
background = "#9b6f9b"

[colors.search.focused_match]
foreground = "#2e3142"
background = "#cbe481"

[colors.footer_bar]
foreground = "#2e3142"
background = "#9b6f9b"

[colors.hints.start]
foreground = "#2e3142"
background = "#e4cb81"

[colors.hints.end]
foreground = "#2e3142"
background = "#9b6f9b"

[colors.selection]
text = "#2e3142"
background = "#7e587e"

[colors.normal]
black = "#434860"
red = "#e48181"
green = "#cbe481"
yellow = "#e4cb81"
blue = "#81e4e4"
magenta = "#e481b3"
cyan = "#81e49a"
white = "#eeb5ee"

[colors.bright]
black = "#434860"
red = "#e48181"
green = "#cbe481"
yellow = "#e4cb81"
blue = "#81e4e4"
magenta = "#e481b3"
cyan = "#81e49a"
white = "#eeb5ee"

[colors.dim]
black = "#434860"
red = "#e48181"
green = "#cbe481"
yellow = "#e4cb81"
blue = "#81e4e4"
magenta = "#e481b3"
cyan = "#81e49a"
white = "#eeb5ee"