[colors.primary]
background = "#b7997b"
foreground = "#000000"
dim_foreground = "#3b312b"
bright_foreground = "#000000"

[colors.cursor]
text = "#b7997b"
cursor = "#000000"

[colors.vi_mode_cursor]
text = "#b7997b"
cursor = "#000000"

[colors.search.matches]
foreground = "#b7997b"
background = "#e4d9ce"

[colors.search.focused_match]
foreground = "#b7997b"
background = "#2d532d"

[colors.footer_bar]
foreground = "#b7997b"
background = "#e4d9ce"

[colors.hints.start]
foreground = "#b7997b"
background = "#404040"

[colors.hints.end]
foreground = "#b7997b"
background = "#e4d9ce"

[colors.selection]
text = "#b7997b"
background = "#d2c0ad"

[colors.normal]
black = "#c9b39c"
red = "#602020"
green = "#2d532d"
yellow = "#404040"
blue = "#2d2d53"
magenta = "#532d53"
cyan = "#2d5353"
white = "#000000"

[colors.bright]
black = "#c9b39c"
red = "#602020"
green = "#2d532d"
yellow = "#404040"
blue = "#2d2d53"
magenta = "#532d53"
cyan = "#2d5353"
white = "#000000"

[colors.dim]
black = "#c9b39c"
red = "#602020"
green = "#2d532d"
yellow = "#404040"
blue = "#2d2d53"
magenta = "#532d53"
cyan = "#2d5353"
white = "#000000"