[colors.primary]
background = "#b7997b"
foreground = "#000000"
dim_foreground = "#3b312b"
bright_foreground = "#000000"

[colors.cursor]
text = "#b7997b"
cursor = "#000000"

[colors.vi_mode_cursor]
text = "#b7997b"
cursor = "#000000"

[colors.search.matches]
foreground = "#b7997b"
background = "#e4d9ce"

[colors.search.focused_match]
foreground = "#b7997b"
background = "#3e743e"

[colors.footer_bar]
foreground = "#b7997b"
background = "#e4d9ce"

[colors.hints.start]
foreground = "#b7997b"
background = "#595959"

[colors.hints.end]
foreground = "#b7997b"
background = "#e4d9ce"

[colors.selection]
text = "#b7997b"
background = "#d2c0ad"

[colors.normal]
black = "#c9b39c"
red = "#862d2d"
green = "#3e743e"
yellow = "#595959"
blue = "#3e3e74"
magenta = "#743e74"
cyan = "#3e7474"
white = "#000000"

[colors.bright]
black = "#c9b39c"
red = "#862d2d"
green = "#3e743e"
yellow = "#595959"
blue = "#3e3e74"
magenta = "#743e74"
cyan = "#3e7474"
white = "#000000"

[colors.dim]
black = "#c9b39c"
red = "#862d2d"
green = "#3e743e"
yellow = "#595959"
blue = "#3e3e74"
magenta = "#743e74"
cyan = "#3e7474"
white = "#000000"