[colors.primary]
background = "#1c171c"
foreground = "#d6c2cc"
dim_foreground = "#ad8599"
bright_foreground = "#d6c2cc"

[colors.cursor]
text = "#1c171c"
cursor = "#d6c2cc"

[colors.vi_mode_cursor]
text = "#1c171c"
cursor = "#d6c2cc"

[colors.search.matches]
foreground = "#1c171c"
background = "#705c70"

[colors.search.focused_match]
foreground = "#1c171c"
background = "#a3ba5e"

[colors.footer_bar]
foreground = "#1c171c"
background = "#705c70"

[colors.hints.start]
foreground = "#1c171c"
background = "#d06a49"

[colors.hints.end]
foreground = "#1c171c"
background = "#705c70"

[colors.selection]
text = "#1c171c"
background = "#544554"

[colors.normal]
black = "#382e38"
red = "#d0496a"
green = "#a3ba5e"
yellow = "#d06a49"
blue = "#8c53c6"
magenta = "#d049ae"
cyan = "#5ebaa3"
white = "#d6c2cc"

[colors.bright]
black = "#382e38"
red = "#d0496a"
green = "#a3ba5e"
yellow = "#d06a49"
blue = "#8c53c6"
magenta = "#d049ae"
cyan = "#5ebaa3"
white = "#d6c2cc"

[colors.dim]
black = "#382e38"
red = "#d0496a"
green = "#a3ba5e"
yellow = "#d06a49"
blue = "#8c53c6"
magenta = "#d049ae"
cyan = "#5ebaa3"
white = "#d6c2cc"