[colors.primary]
background = "#1c171c"
foreground = "#d6c2cc"
dim_foreground = "#ad8599"
bright_foreground = "#d6c2cc"

[colors.cursor]
text = "#1c171c"
cursor = "#d6c2cc"

[colors.vi_mode_cursor]
text = "#1c171c"
cursor = "#d6c2cc"

[colors.search.matches]
foreground = "#1c171c"
background = "#705c70"

[colors.search.focused_match]
foreground = "#1c171c"
background = "#c2d194"

[colors.footer_bar]
foreground = "#1c171c"
background = "#705c70"

[colors.hints.start]
foreground = "#1c171c"
background = "#e09c85"

[colors.hints.end]
foreground = "#1c171c"
background = "#705c70"

[colors.selection]
text = "#1c171c"
background = "#544554"

[colors.normal]
black = "#382e38"
red = "#e0859c"
green = "#c2d194"
yellow = "#e09c85"
blue = "#b38cd9"
magenta = "#e085c9"
cyan = "#94d1c2"
white = "#d6c2cc"

[colors.bright]
black = "#382e38"
red = "#e0859c"
green = "#c2d194"
yellow = "#e09c85"
blue = "#b38cd9"
magenta = "#e085c9"
cyan = "#94d1c2"
white = "#d6c2cc"

[colors.dim]
black = "#382e38"
red = "#e0859c"
green = "#c2d194"
yellow = "#e09c85"
blue = "#b38cd9"
magenta = "#e085c9"
cyan = "#94d1c2"
white = "#d6c2cc"