[colors.primary]
background = "#3d343d"
foreground = "#eeb5ee"
dim_foreground = "#c3acc3"
bright_foreground = "#eeb5ee"

[colors.cursor]
text = "#3d343d"
cursor = "#eeb5ee"

[colors.vi_mode_cursor]
text = "#3d343d"
cursor = "#eeb5ee"

[colors.search.matches]
foreground = "#3d343d"
background = "#8e7b8e"

[colors.search.focused_match]
foreground = "#3d343d"
background = "#c2d194"

[colors.footer_bar]
foreground = "#3d343d"
background = "#8e7b8e"

[colors.hints.start]
foreground = "#3d343d"
background = "#e09c85"

[colors.hints.end]
foreground = "#3d343d"
background = "#8e7b8e"

[colors.selection]
text = "#3d343d"
background = "#746374"

[colors.normal]
black = "#584b58"
red = "#e0859c"
green = "#c2d194"
yellow = "#e09c85"
blue = "#b38cd9"
magenta = "#e085c9"
cyan = "#94d1c2"
white = "#eeb5ee"

[colors.bright]
black = "#584b58"
red = "#e0859c"
green = "#c2d194"
yellow = "#e09c85"
blue = "#b38cd9"
magenta = "#e085c9"
cyan = "#94d1c2"
white = "#eeb5ee"

[colors.dim]
black = "#584b58"
red = "#e0859c"
green = "#c2d194"
yellow = "#e09c85"
blue = "#b38cd9"
magenta = "#e085c9"
cyan = "#94d1c2"
white = "#eeb5ee"