[colors.primary]
background = "#0f1a24"
foreground = "#b8cce0"
dim_foreground = "#859aad"
bright_foreground = "#b8cce0"

[colors.cursor]
text = "#0f1a24"
cursor = "#b8cce0"

[colors.vi_mode_cursor]
text = "#0f1a24"
cursor = "#b8cce0"

[colors.search.matches]
foreground = "#0f1a24"
background = "#52677a"

[colors.search.focused_match]
foreground = "#0f1a24"
background = "#a6e963"

[colors.footer_bar]
foreground = "#0f1a24"
background = "#52677a"

[colors.hints.start]
foreground = "#0f1a24"
background = "#e9e963"

[colors.hints.end]
foreground = "#0f1a24"
background = "#52677a"

[colors.selection]
text = "#0f1a24"
background = "#3d4d5c"

[colors.normal]
black = "#1f3347"
red = "#e963a6"
green = "#a6e963"
yellow = "#e9e963"
blue = "#63c7e9"
magenta = "#7979d2"
cyan = "#63e9a6"
white = "#b8cce0"

[colors.bright]
black = "#1f3347"
red = "#e963a6"
green = "#a6e963"
yellow = "#e9e963"
blue = "#63c7e9"
magenta = "#7979d2"
cyan = "#63e9a6"
white = "#b8cce0"

[colors.dim]
black = "#1f3347"
red = "#e963a6"
green = "#a6e963"
yellow = "#e9e963"
blue = "#63c7e9"
magenta = "#7979d2"
cyan = "#63e9a6"
white = "#b8cce0"