[colors.primary]
background = "#383838"
foreground = "#e2d2c1"
dim_foreground = "#c4b8ab"
bright_foreground = "#e2d2c1"

[colors.cursor]
text = "#383838"
cursor = "#e2d2c1"

[colors.vi_mode_cursor]
text = "#383838"
cursor = "#e2d2c1"

[colors.search.matches]
foreground = "#383838"
background = "#9b856f"

[colors.search.focused_match]
foreground = "#383838"
background = "#99c270"

[colors.footer_bar]
foreground = "#383838"
background = "#9b856f"

[colors.hints.start]
foreground = "#383838"
background = "#d1b561"

[colors.hints.end]
foreground = "#383838"
background = "#9b856f"

[colors.selection]
text = "#383838"
background = "#7e6c58"

[colors.normal]
black = "#525252"
red = "#c27070"
green = "#99c270"
yellow = "#d1b561"
blue = "#ad70c2"
magenta = "#c27099"
cyan = "#70c299"
white = "#e2d2c1"

[colors.bright]
black = "#525252"
red = "#c27070"
green = "#99c270"
yellow = "#d1b561"
blue = "#ad70c2"
magenta = "#c27099"
cyan = "#70c299"
white = "#e2d2c1"

[colors.dim]
black = "#525252"
red = "#c27070"
green = "#99c270"
yellow = "#d1b561"
blue = "#ad70c2"
magenta = "#c27099"
cyan = "#70c299"
white = "#e2d2c1"