[colors.primary]
background = "#F9F5D7"
foreground = "#665C54"
dim_foreground = "#928374"
bright_foreground = "#665C54"

[colors.cursor]
text = "#F9F5D7"
cursor = "#665C54"

[colors.vi_mode_cursor]
text = "#F9F5D7"
cursor = "#665C54"

[colors.search.matches]
foreground = "#F9F5D7"
background = "#bdae93"

[colors.search.focused_match]
foreground = "#F9F5D7"
background = "#9D0006"

[colors.footer_bar]
foreground = "#F9F5D7"
background = "#bdae93"

[colors.hints.start]
foreground = "#F9F5D7"
background = "#79740E"

[colors.hints.end]
foreground = "#F9F5D7"
background = "#bdae93"

[colors.selection]
text = "#F9F5D7"
background = "#d5c4a1"

[colors.normal]
black = "#ebdbb2"
red = "#AF3A03"
green = "#9D0006"
yellow = "#79740E"
blue = "#B57614"
magenta = "#427B58"
cyan = "#076678"
white = "#665C54"

[colors.bright]
black = "#ebdbb2"
red = "#AF3A03"
green = "#9D0006"
yellow = "#79740E"
blue = "#B57614"
magenta = "#427B58"
cyan = "#076678"
white = "#665C54"

[colors.dim]
black = "#ebdbb2"
red = "#AF3A03"
green = "#9D0006"
yellow = "#79740E"
blue = "#B57614"
magenta = "#427B58"
cyan = "#076678"
white = "#665C54"