[colors.primary]
background = "#32302f"
foreground = "#ebdbb2"
dim_foreground = "#bdae93"
bright_foreground = "#ebdbb2"

[colors.cursor]
text = "#32302f"
cursor = "#ebdbb2"

[colors.vi_mode_cursor]
text = "#32302f"
cursor = "#ebdbb2"

[colors.search.matches]
foreground = "#32302f"
background = "#7c6f64"

[colors.search.focused_match]
foreground = "#32302f"
background = "#FB4934"

[colors.footer_bar]
foreground = "#32302f"
background = "#7c6f64"

[colors.hints.start]
foreground = "#32302f"
background = "#B8BB26"

[colors.hints.end]
foreground = "#32302f"
background = "#7c6f64"

[colors.selection]
text = "#32302f"
background = "#665c54"

[colors.normal]
black = "#504945"
red = "#FE8019"
green = "#FB4934"
yellow = "#B8BB26"
blue = "#FABD2F"
magenta = "#8EC07C"
cyan = "#83A598"
white = "#ebdbb2"

[colors.bright]
black = "#504945"
red = "#FE8019"
green = "#FB4934"
yellow = "#B8BB26"
blue = "#FABD2F"
magenta = "#8EC07C"
cyan = "#83A598"
white = "#ebdbb2"

[colors.dim]
black = "#504945"
red = "#FE8019"
green = "#FB4934"
yellow = "#B8BB26"
blue = "#FABD2F"
magenta = "#8EC07C"
cyan = "#83A598"
white = "#ebdbb2"