[colors.primary]
background = "#FBF1C7"
foreground = "#504945"
dim_foreground = "#7c6f64"
bright_foreground = "#504945"

[colors.cursor]
text = "#FBF1C7"
cursor = "#504945"

[colors.vi_mode_cursor]
text = "#FBF1C7"
cursor = "#504945"

[colors.search.matches]
foreground = "#FBF1C7"
background = "#a89984"

[colors.search.focused_match]
foreground = "#FBF1C7"
background = "#9D0006"

[colors.footer_bar]
foreground = "#FBF1C7"
background = "#a89984"

[colors.hints.start]
foreground = "#FBF1C7"
background = "#79740E"

[colors.hints.end]
foreground = "#FBF1C7"
background = "#a89984"

[colors.selection]
text = "#FBF1C7"
background = "#bdae93"

[colors.normal]
black = "#d5c4a1"
red = "#AF3A03"
green = "#9D0006"
yellow = "#79740E"
blue = "#B57614"
magenta = "#427B58"
cyan = "#076678"
white = "#504945"

[colors.bright]
black = "#d5c4a1"
red = "#AF3A03"
green = "#9D0006"
yellow = "#79740E"
blue = "#B57614"
magenta = "#427B58"
cyan = "#076678"
white = "#504945"

[colors.dim]
black = "#d5c4a1"
red = "#AF3A03"
green = "#9D0006"
yellow = "#79740E"
blue = "#B57614"
magenta = "#427B58"
cyan = "#076678"
white = "#504945"