[colors.primary]
background = "#372848"
foreground = "#bfe3c4"
dim_foreground = "#a6c9ab"
bright_foreground = "#bfe3c4"

[colors.cursor]
text = "#372848"
cursor = "#bfe3c4"

[colors.vi_mode_cursor]
text = "#372848"
cursor = "#bfe3c4"

[colors.search.matches]
foreground = "#372848"
background = "#6f9b7a"

[colors.search.focused_match]
foreground = "#372848"
background = "#84e963"

[colors.footer_bar]
foreground = "#372848"
background = "#6f9b7a"

[colors.hints.start]
foreground = "#372848"
background = "#e9e963"

[colors.hints.end]
foreground = "#372848"
background = "#6f9b7a"

[colors.selection]
text = "#372848"
background = "#587e61"

[colors.normal]
black = "#503b68"
red = "#e96363"
green = "#84e963"
yellow = "#e9e963"
blue = "#63e9c7"
magenta = "#d775a6"
cyan = "#63e984"
white = "#bfe3c4"

[colors.bright]
black = "#503b68"
red = "#e96363"
green = "#84e963"
yellow = "#e9e963"
blue = "#63e9c7"
magenta = "#d775a6"
cyan = "#63e984"
white = "#bfe3c4"

[colors.dim]
black = "#503b68"
red = "#e96363"
green = "#84e963"
yellow = "#e9e963"
blue = "#63e9c7"
magenta = "#d775a6"
cyan = "#63e984"
white = "#bfe3c4"