[colors.primary]
background = "#372848"
foreground = "#bfe3c4"
dim_foreground = "#a6c9ab"
bright_foreground = "#bfe3c4"

[colors.cursor]
text = "#372848"
cursor = "#bfe3c4"

[colors.vi_mode_cursor]
text = "#372848"
cursor = "#bfe3c4"

[colors.search.matches]
foreground = "#372848"
background = "#6f9b7a"

[colors.search.focused_match]
foreground = "#372848"
background = "#8dd775"

[colors.footer_bar]
foreground = "#372848"
background = "#6f9b7a"

[colors.hints.start]
foreground = "#372848"
background = "#e0e06c"

[colors.hints.end]
foreground = "#372848"
background = "#6f9b7a"

[colors.selection]
text = "#372848"
background = "#587e61"

[colors.normal]
black = "#503b68"
red = "#e06c6c"
green = "#8dd775"
yellow = "#e0e06c"
blue = "#75d7be"
magenta = "#d775a6"
cyan = "#75d78d"
white = "#bfe3c4"

[colors.bright]
black = "#503b68"
red = "#e06c6c"
green = "#8dd775"
yellow = "#e0e06c"
blue = "#75d7be"
magenta = "#d775a6"
cyan = "#75d78d"
white = "#bfe3c4"

[colors.dim]
black = "#503b68"
red = "#e06c6c"
green = "#8dd775"
yellow = "#e0e06c"
blue = "#75d7be"
magenta = "#d775a6"
cyan = "#75d78d"
white = "#bfe3c4"