[colors.primary]
background = "#372F41"
foreground = "#B3EEBB"
dim_foreground = "#AAC4AE"
bright_foreground = "#B3EEBB"

[colors.cursor]
text = "#372F41"
cursor = "#B3EEBB"

[colors.vi_mode_cursor]
text = "#372F41"
cursor = "#B3EEBB"

[colors.search.matches]
foreground = "#372F41"
background = "#6E9A79"

[colors.search.focused_match]
foreground = "#372F41"
background = "#9ED88C"

[colors.footer_bar]
foreground = "#372F41"
background = "#6E9A79"

[colors.hints.start]
foreground = "#372F41"
background = "#D8D88C"

[colors.hints.end]
foreground = "#372F41"
background = "#6E9A79"

[colors.selection]
text = "#372F41"
background = "#577E60"

[colors.normal]
black = "#50445E"
red = "#D88C8C"
green = "#9ED88C"
yellow = "#D8D88C"
blue = "#8CD8C5"
magenta = "#D88CB2"
cyan = "#8CD89E"
white = "#B3EEBB"

[colors.bright]
black = "#50445E"
red = "#D88C8C"
green = "#9ED88C"
yellow = "#D8D88C"
blue = "#8CD8C5"
magenta = "#D88CB2"
cyan = "#8CD89E"
white = "#B3EEBB"

[colors.dim]
black = "#50445E"
red = "#D88C8C"
green = "#9ED88C"
yellow = "#D8D88C"
blue = "#8CD8C5"
magenta = "#D88CB2"
cyan = "#8CD89E"
white = "#B3EEBB"