[colors.primary]
background = "#171c1c"
foreground = "#c7ccd1"
dim_foreground = "#8f9aa3"
bright_foreground = "#c7ccd1"

[colors.cursor]
text = "#171c1c"
cursor = "#c7ccd1"

[colors.vi_mode_cursor]
text = "#171c1c"
cursor = "#c7ccd1"

[colors.search.matches]
foreground = "#171c1c"
background = "#5c6770"

[colors.search.focused_match]
foreground = "#171c1c"
background = "#98e6ac"

[colors.footer_bar]
foreground = "#171c1c"
background = "#5c6770"

[colors.hints.start]
foreground = "#171c1c"
background = "#e6d398"

[colors.hints.end]
foreground = "#171c1c"
background = "#5c6770"

[colors.selection]
text = "#171c1c"
background = "#454d54"

[colors.normal]
black = "#2e3838"
red = "#e6ac98"
green = "#98e6ac"
yellow = "#e6d398"
blue = "#98d3e6"
magenta = "#e698bf"
cyan = "#98e6d3"
white = "#c7ccd1"

[colors.bright]
black = "#2e3838"
red = "#e6ac98"
green = "#98e6ac"
yellow = "#e6d398"
blue = "#98d3e6"
magenta = "#e698bf"
cyan = "#98e6d3"
white = "#c7ccd1"

[colors.dim]
black = "#2e3838"
red = "#e6ac98"
green = "#98e6ac"
yellow = "#e6d398"
blue = "#98d3e6"
magenta = "#e698bf"
cyan = "#98e6d3"
white = "#c7ccd1"