[colors.primary]
background = "#1f2a2e"
foreground = "#d0dae1"
dim_foreground = "#92a9b9"
bright_foreground = "#d0dae1"

[colors.cursor]
text = "#1f2a2e"
cursor = "#d0dae1"

[colors.vi_mode_cursor]
text = "#1f2a2e"
cursor = "#d0dae1"

[colors.search.matches]
foreground = "#1f2a2e"
background = "#677e7e"

[colors.search.focused_match]
foreground = "#1f2a2e"
background = "#9fd98c"

[colors.footer_bar]
foreground = "#1f2a2e"
background = "#677e7e"

[colors.hints.start]
foreground = "#1f2a2e"
background = "#f2da8c"

[colors.hints.end]
foreground = "#1f2a2e"
background = "#677e7e"

[colors.selection]
text = "#1f2a2e"
background = "#506262"

[colors.normal]
black = "#34454c"
red = "#d27979"
green = "#9fd98c"
yellow = "#f2da8c"
blue = "#80a6cb"
magenta = "#d194b3"
cyan = "#8cd9c6"
white = "#d0dae1"

[colors.bright]
black = "#34454c"
red = "#d27979"
green = "#9fd98c"
yellow = "#f2da8c"
blue = "#80a6cb"
magenta = "#d194b3"
cyan = "#8cd9c6"
white = "#d0dae1"

[colors.dim]
black = "#34454c"
red = "#d27979"
green = "#9fd98c"
yellow = "#f2da8c"
blue = "#80a6cb"
magenta = "#d194b3"
cyan = "#8cd9c6"
white = "#d0dae1"