[colors.primary]
background = "#ceced4"
foreground = "#1d1d20"
dim_foreground = "#4d4d56"
bright_foreground = "#1d1d20"

[colors.cursor]
text = "#ceced4"
cursor = "#1d1d20"

[colors.vi_mode_cursor]
text = "#ceced4"
cursor = "#1d1d20"

[colors.search.matches]
foreground = "#ceced4"
background = "#7d7d8c"

[colors.search.focused_match]
foreground = "#ceced4"
background = "#648267"

[colors.footer_bar]
foreground = "#ceced4"
background = "#7d7d8c"

[colors.hints.start]
foreground = "#ceced4"
background = "#c37d22"

[colors.hints.end]
foreground = "#ceced4"
background = "#7d7d8c"

[colors.selection]
text = "#ceced4"
background = "#9898a4"

[colors.normal]
black = "#b3b3bc"
red = "#ac393b"
green = "#648267"
yellow = "#c37d22"
blue = "#4b879b"
magenta = "#644e97"
cyan = "#4b9b87"
white = "#1d1d20"

[colors.bright]
black = "#b3b3bc"
red = "#ac393b"
green = "#648267"
yellow = "#c37d22"
blue = "#4b879b"
magenta = "#644e97"
cyan = "#4b9b87"
white = "#1d1d20"

[colors.dim]
black = "#b3b3bc"
red = "#ac393b"
green = "#648267"
yellow = "#c37d22"
blue = "#4b879b"
magenta = "#644e97"
cyan = "#4b9b87"
white = "#1d1d20"