[colors.primary]
background = "#19191a"
foreground = "#c7c7d1"
dim_foreground = "#8f8fa3"
bright_foreground = "#c7c7d1"

[colors.cursor]
text = "#19191a"
cursor = "#c7c7d1"

[colors.vi_mode_cursor]
text = "#19191a"
cursor = "#c7c7d1"

[colors.search.matches]
foreground = "#19191a"
background = "#61616b"

[colors.search.focused_match]
foreground = "#19191a"
background = "#648267"

[colors.footer_bar]
foreground = "#19191a"
background = "#61616b"

[colors.hints.start]
foreground = "#19191a"
background = "#e0a352"

[colors.hints.end]
foreground = "#19191a"
background = "#61616b"

[colors.selection]
text = "#19191a"
background = "#494950"

[colors.normal]
black = "#323234"
red = "#c65355"
green = "#648267"
yellow = "#e0a352"
blue = "#5396ac"
magenta = "#8c78ba"
cyan = "#53ac96"
white = "#c7c7d1"

[colors.bright]
black = "#323234"
red = "#c65355"
green = "#648267"
yellow = "#e0a352"
blue = "#5396ac"
magenta = "#8c78ba"
cyan = "#53ac96"
white = "#c7c7d1"

[colors.dim]
black = "#323234"
red = "#c65355"
green = "#648267"
yellow = "#e0a352"
blue = "#5396ac"
magenta = "#8c78ba"
cyan = "#53ac96"
white = "#c7c7d1"