[colors.primary]
background = "#35353b"
foreground = "#e9e9ec"
dim_foreground = "#b3b3bc"
bright_foreground = "#e9e9ec"

[colors.cursor]
text = "#35353b"
cursor = "#e9e9ec"

[colors.vi_mode_cursor]
text = "#35353b"
cursor = "#e9e9ec"

[colors.search.matches]
foreground = "#35353b"
background = "#7d7d8c"

[colors.search.focused_match]
foreground = "#35353b"
background = "#648267"

[colors.footer_bar]
foreground = "#35353b"
background = "#7d7d8c"

[colors.hints.start]
foreground = "#35353b"
background = "#e0a352"

[colors.hints.end]
foreground = "#35353b"
background = "#7d7d8c"

[colors.selection]
text = "#35353b"
background = "#656572"

[colors.normal]
black = "#4d4d56"
red = "#c65355"
green = "#648267"
yellow = "#e0a352"
blue = "#5396ac"
magenta = "#8c78ba"
cyan = "#53ac96"
white = "#e9e9ec"

[colors.bright]
black = "#4d4d56"
red = "#c65355"
green = "#648267"
yellow = "#e0a352"
blue = "#5396ac"
magenta = "#8c78ba"
cyan = "#53ac96"
white = "#e9e9ec"

[colors.dim]
black = "#4d4d56"
red = "#c65355"
green = "#648267"
yellow = "#e0a352"
blue = "#5396ac"
magenta = "#8c78ba"
cyan = "#53ac96"
white = "#e9e9ec"