[colors.primary]
background = "#2e2e42"
foreground = "#e9d9ba"
dim_foreground = "#c9b58d"
bright_foreground = "#e9d9ba"

[colors.cursor]
text = "#2e2e42"
cursor = "#e9d9ba"

[colors.vi_mode_cursor]
text = "#2e2e42"
cursor = "#e9d9ba"

[colors.search.matches]
foreground = "#2e2e42"
background = "#6f6f9b"

[colors.search.focused_match]
foreground = "#2e2e42"
background = "#70db8b"

[colors.footer_bar]
foreground = "#2e2e42"
background = "#6f6f9b"

[colors.hints.start]
foreground = "#2e2e42"
background = "#dbc170"

[colors.hints.end]
foreground = "#2e2e42"
background = "#6f6f9b"

[colors.selection]
text = "#2e2e42"
background = "#58587e"

[colors.normal]
black = "#434360"
red = "#db8b70"
green = "#70db8b"
yellow = "#dbc170"
blue = "#70c1db"
magenta = "#8f79d2"
cyan = "#70dbc1"
white = "#e9d9ba"

[colors.bright]
black = "#434360"
red = "#db8b70"
green = "#70db8b"
yellow = "#dbc170"
blue = "#70c1db"
magenta = "#8f79d2"
cyan = "#70dbc1"
white = "#e9d9ba"

[colors.dim]
black = "#434360"
red = "#db8b70"
green = "#70db8b"
yellow = "#dbc170"
blue = "#70c1db"
magenta = "#8f79d2"
cyan = "#70dbc1"
white = "#e9d9ba"