[colors.primary]
background = "#282a22"
foreground = "#dddbd5"
dim_foreground = "#afac9d"
bright_foreground = "#dddbd5"

[colors.cursor]
text = "#282a22"
cursor = "#dddbd5"

[colors.vi_mode_cursor]
text = "#282a22"
cursor = "#dddbd5"

[colors.search.matches]
foreground = "#282a22"
background = "#7e7a67"

[colors.search.focused_match]
foreground = "#282a22"
background = "#b3d98c"

[colors.footer_bar]
foreground = "#282a22"
background = "#7e7a67"

[colors.hints.start]
foreground = "#282a22"
background = "#d9d98c"

[colors.hints.end]
foreground = "#282a22"
background = "#7e7a67"

[colors.selection]
text = "#282a22"
background = "#625f50"

[colors.normal]
black = "#434739"
red = "#d98c9f"
green = "#b3d98c"
yellow = "#d9d98c"
blue = "#8cc6d9"
magenta = "#bfa6d9"
cyan = "#8cd9c6"
white = "#dddbd5"

[colors.bright]
black = "#434739"
red = "#d98c9f"
green = "#b3d98c"
yellow = "#d9d98c"
blue = "#8cc6d9"
magenta = "#bfa6d9"
cyan = "#8cd9c6"
white = "#dddbd5"

[colors.dim]
black = "#434739"
red = "#d98c9f"
green = "#b3d98c"
yellow = "#d9d98c"
blue = "#8cc6d9"
magenta = "#bfa6d9"
cyan = "#8cd9c6"
white = "#dddbd5"