[colors.primary]
background = "#3a3d34"
foreground = "#e7e0bb"
dim_foreground = "#c0bdaf"
bright_foreground = "#e7e0bb"

[colors.cursor]
text = "#3a3d34"
cursor = "#e7e0bb"

[colors.vi_mode_cursor]
text = "#3a3d34"
cursor = "#e7e0bb"

[colors.search.matches]
foreground = "#3a3d34"
background = "#938e76"

[colors.search.focused_match]
foreground = "#3a3d34"
background = "#c2d194"

[colors.footer_bar]
foreground = "#3a3d34"
background = "#938e76"

[colors.hints.start]
foreground = "#3a3d34"
background = "#e09c85"

[colors.hints.end]
foreground = "#3a3d34"
background = "#938e76"

[colors.selection]
text = "#3a3d34"
background = "#78745e"

[colors.normal]
black = "#54584b"
red = "#e0859c"
green = "#c2d194"
yellow = "#e09c85"
blue = "#b38cd9"
magenta = "#e085c9"
cyan = "#94d1c2"
white = "#e7e0bb"

[colors.bright]
black = "#54584b"
red = "#e0859c"
green = "#c2d194"
yellow = "#e09c85"
blue = "#b38cd9"
magenta = "#e085c9"
cyan = "#94d1c2"
white = "#e7e0bb"

[colors.dim]
black = "#54584b"
red = "#e0859c"
green = "#c2d194"
yellow = "#e09c85"
blue = "#b38cd9"
magenta = "#e085c9"
cyan = "#94d1c2"
white = "#e7e0bb"