[colors.primary]
background = "#3a3d34"
foreground = "#e7e0bb"
dim_foreground = "#c0bdaf"
bright_foreground = "#e7e0bb"

[colors.cursor]
text = "#3a3d34"
cursor = "#e7e0bb"

[colors.vi_mode_cursor]
text = "#3a3d34"
cursor = "#e7e0bb"

[colors.search.matches]
foreground = "#3a3d34"
background = "#938e76"

[colors.search.focused_match]
foreground = "#3a3d34"
background = "#9ddd88"

[colors.footer_bar]
foreground = "#3a3d34"
background = "#938e76"

[colors.hints.start]
foreground = "#3a3d34"
background = "#d9d98c"

[colors.hints.end]
foreground = "#3a3d34"
background = "#938e76"

[colors.selection]
text = "#3a3d34"
background = "#78745e"

[colors.normal]
black = "#54584b"
red = "#dd889d"
green = "#9ddd88"
yellow = "#d9d98c"
blue = "#88b3dd"
magenta = "#d98cc6"
cyan = "#88ddc8"
white = "#e7e0bb"

[colors.bright]
black = "#54584b"
red = "#dd889d"
green = "#9ddd88"
yellow = "#d9d98c"
blue = "#88b3dd"
magenta = "#d98cc6"
cyan = "#88ddc8"
white = "#e7e0bb"

[colors.dim]
black = "#54584b"
red = "#dd889d"
green = "#9ddd88"
yellow = "#d9d98c"
blue = "#88b3dd"
magenta = "#d98cc6"
cyan = "#88ddc8"
white = "#e7e0bb"