[colors.primary]
background = "#3a3d34"
foreground = "#e7e0bb"
dim_foreground = "#c0bdaf"
bright_foreground = "#e7e0bb"

[colors.cursor]
text = "#3a3d34"
cursor = "#e7e0bb"

[colors.vi_mode_cursor]
text = "#3a3d34"
cursor = "#e7e0bb"

[colors.search.matches]
foreground = "#3a3d34"
background = "#938e76"

[colors.search.focused_match]
foreground = "#3a3d34"
background = "#8cd9b3"

[colors.footer_bar]
foreground = "#3a3d34"
background = "#938e76"

[colors.hints.start]
foreground = "#3a3d34"
background = "#c8dd88"

[colors.hints.end]
foreground = "#3a3d34"
background = "#938e76"

[colors.selection]
text = "#3a3d34"
background = "#78745e"

[colors.normal]
black = "#54584b"
red = "#dd889d"
green = "#8cd9b3"
yellow = "#c8dd88"
blue = "#8c9fd9"
magenta = "#d98cc6"
cyan = "#8cc6d9"
white = "#e7e0bb"

[colors.bright]
black = "#54584b"
red = "#dd889d"
green = "#8cd9b3"
yellow = "#c8dd88"
blue = "#8c9fd9"
magenta = "#d98cc6"
cyan = "#8cc6d9"
white = "#e7e0bb"

[colors.dim]
black = "#54584b"
red = "#dd889d"
green = "#8cd9b3"
yellow = "#c8dd88"
blue = "#8c9fd9"
magenta = "#d98cc6"
cyan = "#8cc6d9"
white = "#e7e0bb"