[colors.primary]
background = "#2f4141"
foreground = "#b4deee"
dim_foreground = "#acbdc3"
bright_foreground = "#b4deee"

[colors.cursor]
text = "#2f4141"
cursor = "#b4deee"

[colors.vi_mode_cursor]
text = "#2f4141"
cursor = "#b4deee"

[colors.search.matches]
foreground = "#2f4141"
background = "#718d98"

[colors.search.focused_match]
foreground = "#2f4141"
background = "#8cd9b3"

[colors.footer_bar]
foreground = "#2f4141"
background = "#718d98"

[colors.hints.start]
foreground = "#2f4141"
background = "#e3e6b3"

[colors.hints.end]
foreground = "#2f4141"
background = "#718d98"

[colors.selection]
text = "#2f4141"
background = "#5a737c"

[colors.normal]
black = "#455f5f"
red = "#e87d98"
green = "#8cd9b3"
yellow = "#e3e6b3"
blue = "#79a6d2"
magenta = "#df9fcf"
cyan = "#8cd9d9"
white = "#b4deee"

[colors.bright]
black = "#455f5f"
red = "#e87d98"
green = "#8cd9b3"
yellow = "#e3e6b3"
blue = "#79a6d2"
magenta = "#df9fcf"
cyan = "#8cd9d9"
white = "#b4deee"

[colors.dim]
black = "#455f5f"
red = "#e87d98"
green = "#8cd9b3"
yellow = "#e3e6b3"
blue = "#79a6d2"
magenta = "#df9fcf"
cyan = "#8cd9d9"
white = "#b4deee"