[colors.primary]
background = "#24212c"
foreground = "#c2c2f0"
dim_foreground = "#8282c9"
bright_foreground = "#c2c2f0"

[colors.cursor]
text = "#24212c"
cursor = "#c2c2f0"

[colors.vi_mode_cursor]
text = "#24212c"
cursor = "#c2c2f0"

[colors.search.matches]
foreground = "#24212c"
background = "#6b6383"

[colors.search.focused_match]
foreground = "#24212c"
background = "#bff28c"

[colors.footer_bar]
foreground = "#24212c"
background = "#6b6383"

[colors.hints.start]
foreground = "#24212c"
background = "#80bfff"

[colors.hints.end]
foreground = "#24212c"
background = "#6b6383"

[colors.selection]
text = "#24212c"
background = "#534d66"

[colors.normal]
black = "#3c3749"
red = "#f28c8c"
green = "#bff28c"
yellow = "#80bfff"
blue = "#f0c775"
magenta = "#8cf2f2"
cyan = "#f28cf2"
white = "#c2c2f0"

[colors.bright]
black = "#3c3749"
red = "#f28c8c"
green = "#bff28c"
yellow = "#80bfff"
blue = "#f0c775"
magenta = "#8cf2f2"
cyan = "#f28cf2"
white = "#c2c2f0"

[colors.dim]
black = "#3c3749"
red = "#f28c8c"
green = "#bff28c"
yellow = "#80bfff"
blue = "#f0c775"
magenta = "#8cf2f2"
cyan = "#f28cf2"
white = "#c2c2f0"