[colors.primary]
background = "#37343d"
foreground = "#cacad8"
dim_foreground = "#b2b2bd"
bright_foreground = "#cacad8"

[colors.cursor]
text = "#37343d"
cursor = "#cacad8"

[colors.vi_mode_cursor]
text = "#37343d"
cursor = "#cacad8"

[colors.search.matches]
foreground = "#37343d"
background = "#a36674"

[colors.search.focused_match]
foreground = "#37343d"
background = "#b5c587"

[colors.footer_bar]
foreground = "#37343d"
background = "#a36674"

[colors.hints.start]
foreground = "#37343d"
background = "#c99482"

[colors.hints.end]
foreground = "#37343d"
background = "#a36674"

[colors.selection]
text = "#37343d"
background = "#86505d"

[colors.normal]
black = "#504c59"
red = "#c587a7"
green = "#b5c587"
yellow = "#c99482"
blue = "#988bc1"
magenta = "#c18bc1"
cyan = "#9fc6c6"
white = "#cacad8"

[colors.bright]
black = "#504c59"
red = "#c587a7"
green = "#b5c587"
yellow = "#c99482"
blue = "#988bc1"
magenta = "#c18bc1"
cyan = "#9fc6c6"
white = "#cacad8"

[colors.dim]
black = "#504c59"
red = "#c587a7"
green = "#b5c587"
yellow = "#c99482"
blue = "#988bc1"
magenta = "#c18bc1"
cyan = "#9fc6c6"
white = "#cacad8"