[colors.primary]
background = "#333333"
foreground = "#e6e6e6"
dim_foreground = "#b3b3b3"
bright_foreground = "#e6e6e6"

[colors.cursor]
text = "#333333"
cursor = "#e6e6e6"

[colors.vi_mode_cursor]
text = "#333333"
cursor = "#e6e6e6"

[colors.search.matches]
foreground = "#333333"
background = "#808080"

[colors.search.focused_match]
foreground = "#333333"
background = "#52e052"

[colors.footer_bar]
foreground = "#333333"
background = "#808080"

[colors.hints.start]
foreground = "#333333"
background = "#f0f075"

[colors.hints.end]
foreground = "#333333"
background = "#808080"

[colors.selection]
text = "#333333"
background = "#666666"

[colors.normal]
black = "#4d4d4d"
red = "#e05252"
green = "#52e052"
yellow = "#f0f075"
blue = "#5299e0"
magenta = "#d161b5"
cyan = "#52e0e0"
white = "#e6e6e6"

[colors.bright]
black = "#4d4d4d"
red = "#e05252"
green = "#52e052"
yellow = "#f0f075"
blue = "#5299e0"
magenta = "#d161b5"
cyan = "#52e0e0"
white = "#e6e6e6"

[colors.dim]
black = "#4d4d4d"
red = "#e05252"
green = "#52e052"
yellow = "#f0f075"
blue = "#5299e0"
magenta = "#d161b5"
cyan = "#52e0e0"
white = "#e6e6e6"