[colors.primary]
background = "#e3bfc1"
foreground = "#281517"
dim_foreground = "#6a393c"
bright_foreground = "#281517"

[colors.cursor]
text = "#e3bfc1"
cursor = "#281517"

[colors.vi_mode_cursor]
text = "#e3bfc1"
cursor = "#281517"

[colors.search.matches]
foreground = "#e3bfc1"
background = "#a96065"

[colors.search.focused_match]
foreground = "#e3bfc1"
background = "#687d73"

[colors.footer_bar]
foreground = "#e3bfc1"
background = "#a96065"

[colors.hints.start]
foreground = "#e3bfc1"
background = "#28383e"

[colors.hints.end]
foreground = "#e3bfc1"
background = "#a96065"

[colors.selection]
text = "#e3bfc1"
background = "#bb8185"

[colors.normal]
black = "#d49b9f"
red = "#c65353"
green = "#687d73"
yellow = "#28383e"
blue = "#1f5993"
magenta = "#6b6b94"
cyan = "#3492b2"
white = "#281517"

[colors.bright]
black = "#d49b9f"
red = "#c65353"
green = "#687d73"
yellow = "#28383e"
blue = "#1f5993"
magenta = "#6b6b94"
cyan = "#3492b2"
white = "#281517"

[colors.dim]
black = "#d49b9f"
red = "#c65353"
green = "#687d73"
yellow = "#28383e"
blue = "#1f5993"
magenta = "#6b6b94"
cyan = "#3492b2"
white = "#281517"