[colors.primary]
background = "#48282c"
foreground = "#ebb7bd"
dim_foreground = "#cca4a8"
bright_foreground = "#ebb7bd"

[colors.cursor]
text = "#48282c"
cursor = "#ebb7bd"

[colors.vi_mode_cursor]
text = "#48282c"
cursor = "#ebb7bd"

[colors.search.matches]
foreground = "#48282c"
background = "#a76269"

[colors.search.focused_match]
foreground = "#48282c"
background = "#8cd9b8"

[colors.footer_bar]
foreground = "#48282c"
background = "#a76269"

[colors.hints.start]
foreground = "#48282c"
background = "#56848f"

[colors.hints.end]
foreground = "#48282c"
background = "#a76269"

[colors.selection]
text = "#48282c"
background = "#894d53"

[colors.normal]
black = "#683b3f"
red = "#e75a5a"
green = "#8cd9b8"
yellow = "#56848f"
blue = "#1f6dad"
magenta = "#6a6aaf"
cyan = "#5fb8d3"
white = "#ebb7bd"

[colors.bright]
black = "#683b3f"
red = "#e75a5a"
green = "#8cd9b8"
yellow = "#56848f"
blue = "#1f6dad"
magenta = "#6a6aaf"
cyan = "#5fb8d3"
white = "#ebb7bd"

[colors.dim]
black = "#683b3f"
red = "#e75a5a"
green = "#8cd9b8"
yellow = "#56848f"
blue = "#1f6dad"
magenta = "#6a6aaf"
cyan = "#5fb8d3"
white = "#ebb7bd"