[colors.primary]
background = "#333333"
foreground = "#e2edde"
dim_foreground = "#a7c99c"
bright_foreground = "#e2edde"

[colors.cursor]
text = "#333333"
cursor = "#e2edde"

[colors.vi_mode_cursor]
text = "#333333"
cursor = "#e2edde"

[colors.search.matches]
foreground = "#333333"
background = "#59a66c"

[colors.search.focused_match]
foreground = "#333333"
background = "#97e97c"

[colors.footer_bar]
foreground = "#333333"
background = "#59a66c"

[colors.hints.start]
foreground = "#333333"
background = "#e9e97c"

[colors.hints.end]
foreground = "#333333"
background = "#59a66c"

[colors.selection]
text = "#333333"
background = "#478557"

[colors.normal]
black = "#4d4d4d"
red = "#e9977c"
green = "#97e97c"
yellow = "#e9e97c"
blue = "#7ccee9"
magenta = "#e97c97"
cyan = "#7ce9ce"
white = "#e2edde"

[colors.bright]
black = "#4d4d4d"
red = "#e9977c"
green = "#97e97c"
yellow = "#e9e97c"
blue = "#7ccee9"
magenta = "#e97c97"
cyan = "#7ce9ce"
white = "#e2edde"

[colors.dim]
black = "#4d4d4d"
red = "#e9977c"
green = "#97e97c"
yellow = "#e9e97c"
blue = "#7ccee9"
magenta = "#e97c97"
cyan = "#7ce9ce"
white = "#e2edde"