[colors.primary]
background = "#383838"
foreground = "#b4eec2"
dim_foreground = "#abc4b1"
bright_foreground = "#b4eec2"

[colors.cursor]
text = "#383838"
cursor = "#b4eec2"

[colors.vi_mode_cursor]
text = "#383838"
cursor = "#b4eec2"

[colors.search.matches]
foreground = "#383838"
background = "#6f9b7a"

[colors.search.focused_match]
foreground = "#383838"
background = "#97e97c"

[colors.footer_bar]
foreground = "#383838"
background = "#6f9b7a"

[colors.hints.start]
foreground = "#383838"
background = "#e9e97c"

[colors.hints.end]
foreground = "#383838"
background = "#6f9b7a"

[colors.selection]
text = "#383838"
background = "#587e61"

[colors.normal]
black = "#525252"
red = "#e9977c"
green = "#97e97c"
yellow = "#e9e97c"
blue = "#7ccee9"
magenta = "#e97c97"
cyan = "#7ce9ce"
white = "#b4eec2"

[colors.bright]
black = "#525252"
red = "#e9977c"
green = "#97e97c"
yellow = "#e9e97c"
blue = "#7ccee9"
magenta = "#e97c97"
cyan = "#7ce9ce"
white = "#b4eec2"

[colors.dim]
black = "#525252"
red = "#e9977c"
green = "#97e97c"
yellow = "#e9e97c"
blue = "#7ccee9"
magenta = "#e97c97"
cyan = "#7ce9ce"
white = "#b4eec2"