[colors.primary]
background = "#283f48"
foreground = "#eceee8"
dim_foreground = "#bec2ad"
bright_foreground = "#eceee8"

[colors.cursor]
text = "#283f48"
cursor = "#eceee8"

[colors.vi_mode_cursor]
text = "#283f48"
cursor = "#eceee8"

[colors.search.matches]
foreground = "#283f48"
background = "#728c97"

[colors.search.focused_match]
foreground = "#283f48"
background = "#afe085"

[colors.footer_bar]
foreground = "#283f48"
background = "#728c97"

[colors.hints.start]
foreground = "#283f48"
background = "#ebba47"

[colors.hints.end]
foreground = "#283f48"
background = "#728c97"

[colors.selection]
text = "#283f48"
background = "#5b727b"

[colors.normal]
black = "#3b5c68"
red = "#eb474a"
green = "#afe085"
yellow = "#ebba47"
blue = "#61a6d1"
magenta = "#F0F3BD"
cyan = "#61d1b1"
white = "#eceee8"

[colors.bright]
black = "#3b5c68"
red = "#eb474a"
green = "#afe085"
yellow = "#ebba47"
blue = "#61a6d1"
magenta = "#F0F3BD"
cyan = "#61d1b1"
white = "#eceee8"

[colors.dim]
black = "#3b5c68"
red = "#eb474a"
green = "#afe085"
yellow = "#ebba47"
blue = "#61a6d1"
magenta = "#F0F3BD"
cyan = "#61d1b1"
white = "#eceee8"