[colors.primary]
background = "#422e2e"
foreground = "#eedbb4"
dim_foreground = "#dac395"
bright_foreground = "#eedbb4"

[colors.cursor]
text = "#422e2e"
cursor = "#eedbb4"

[colors.vi_mode_cursor]
text = "#422e2e"
cursor = "#eedbb4"

[colors.search.matches]
foreground = "#422e2e"
background = "#9b6f6f"

[colors.search.focused_match]
foreground = "#422e2e"
background = "#75ba5e"

[colors.footer_bar]
foreground = "#422e2e"
background = "#9b6f6f"

[colors.hints.start]
foreground = "#422e2e"
background = "#e0c36c"

[colors.hints.end]
foreground = "#422e2e"
background = "#9b6f6f"

[colors.selection]
text = "#422e2e"
background = "#7e5858"

[colors.normal]
black = "#604343"
red = "#ba5e5e"
green = "#75ba5e"
yellow = "#e0c36c"
blue = "#7575a3"
magenta = "#ba5e8c"
cyan = "#75a3a3"
white = "#eedbb4"

[colors.bright]
black = "#604343"
red = "#ba5e5e"
green = "#75ba5e"
yellow = "#e0c36c"
blue = "#7575a3"
magenta = "#ba5e8c"
cyan = "#75a3a3"
white = "#eedbb4"

[colors.dim]
black = "#604343"
red = "#ba5e5e"
green = "#75ba5e"
yellow = "#e0c36c"
blue = "#7575a3"
magenta = "#ba5e8c"
cyan = "#75a3a3"
white = "#eedbb4"