[colors.primary]
background = "#191919"
foreground = "#D3D4C6"
dim_foreground = "#A5A88B"
bright_foreground = "#D3D4C6"

[colors.cursor]
text = "#191919"
cursor = "#D3D4C6"

[colors.vi_mode_cursor]
text = "#191919"
cursor = "#D3D4C6"

[colors.search.matches]
foreground = "#191919"
background = "#717457"

[colors.search.focused_match]
foreground = "#191919"
background = "#b3dd88"

[colors.footer_bar]
foreground = "#191919"
background = "#717457"

[colors.hints.start]
foreground = "#191919"
background = "#d9d98c"

[colors.hints.end]
foreground = "#191919"
background = "#717457"

[colors.selection]
text = "#191919"
background = "#555741"

[colors.normal]
black = "#333333"
red = "#dd889d"
green = "#b3dd88"
yellow = "#d9d98c"
blue = "#88dddd"
magenta = "#d194c3"
cyan = "#85e0b3"
white = "#D3D4C6"

[colors.bright]
black = "#333333"
red = "#dd889d"
green = "#b3dd88"
yellow = "#d9d98c"
blue = "#88dddd"
magenta = "#d194c3"
cyan = "#85e0b3"
white = "#D3D4C6"

[colors.dim]
black = "#333333"
red = "#dd889d"
green = "#b3dd88"
yellow = "#d9d98c"
blue = "#88dddd"
magenta = "#d194c3"
cyan = "#85e0b3"
white = "#D3D4C6"