[colors.primary]
background = "#2e4238"
foreground = "#c4d8de"
dim_foreground = "#abbec4"
bright_foreground = "#c4d8de"

[colors.cursor]
text = "#2e4238"
cursor = "#c4d8de"

[colors.vi_mode_cursor]
text = "#2e4238"
cursor = "#c4d8de"

[colors.search.matches]
foreground = "#2e4238"
background = "#6f909b"

[colors.search.focused_match]
foreground = "#2e4238"
background = "#b3d194"

[colors.footer_bar]
foreground = "#2e4238"
background = "#6f909b"

[colors.hints.start]
foreground = "#2e4238"
background = "#d1d194"

[colors.hints.end]
foreground = "#2e4238"
background = "#6f909b"

[colors.selection]
text = "#2e4238"
background = "#58757e"

[colors.normal]
black = "#436052"
red = "#d194a3"
green = "#b3d194"
yellow = "#d1d194"
blue = "#94c2d1"
magenta = "#d194c2"
cyan = "#94d1b3"
white = "#c4d8de"

[colors.bright]
black = "#436052"
red = "#d194a3"
green = "#b3d194"
yellow = "#d1d194"
blue = "#94c2d1"
magenta = "#d194c2"
cyan = "#94d1b3"
white = "#c4d8de"

[colors.dim]
black = "#436052"
red = "#d194a3"
green = "#b3d194"
yellow = "#d1d194"
blue = "#94c2d1"
magenta = "#d194c2"
cyan = "#94d1b3"
white = "#c4d8de"