[colors.primary]
background = "#260d0d"
foreground = "#eacdae"
dim_foreground = "#d59b5d"
bright_foreground = "#eacdae"

[colors.cursor]
text = "#260d0d"
cursor = "#eacdae"

[colors.vi_mode_cursor]
text = "#260d0d"
cursor = "#eacdae"

[colors.search.matches]
foreground = "#260d0d"
background = "#a2682a"

[colors.search.focused_match]
foreground = "#260d0d"
background = "#eda65e"

[colors.footer_bar]
foreground = "#260d0d"
background = "#a2682a"

[colors.hints.start]
foreground = "#260d0d"
background = "#ed5e5e"

[colors.hints.end]
foreground = "#260d0d"
background = "#a2682a"

[colors.selection]
text = "#260d0d"
background = "#7a4e1f"

[colors.normal]
black = "#4b1b1b"
red = "#ed5e82"
green = "#eda65e"
yellow = "#ed5e5e"
blue = "#e4e467"
magenta = "#ed825e"
cyan = "#edc95e"
white = "#eacdae"

[colors.bright]
black = "#4b1b1b"
red = "#ed5e82"
green = "#eda65e"
yellow = "#ed5e5e"
blue = "#e4e467"
magenta = "#ed825e"
cyan = "#edc95e"
white = "#eacdae"

[colors.dim]
black = "#4b1b1b"
red = "#ed5e82"
green = "#eda65e"
yellow = "#ed5e5e"
blue = "#e4e467"
magenta = "#ed825e"
cyan = "#edc95e"
white = "#eacdae"