[colors.primary]
background = "#383838"
foreground = "#eedfb4"
dim_foreground = "#c4beab"
bright_foreground = "#eedfb4"

[colors.cursor]
text = "#383838"
cursor = "#eedfb4"

[colors.vi_mode_cursor]
text = "#383838"
cursor = "#eedfb4"

[colors.search.matches]
foreground = "#383838"
background = "#9b6f7a"

[colors.search.focused_match]
foreground = "#383838"
background = "#7ab88a"

[colors.footer_bar]
foreground = "#383838"
background = "#9b6f7a"

[colors.hints.start]
foreground = "#383838"
background = "#c2c270"

[colors.hints.end]
foreground = "#383838"
background = "#9b6f7a"

[colors.selection]
text = "#383838"
background = "#7e5861"

[colors.normal]
black = "#525252"
red = "#b87a7a"
green = "#7ab88a"
yellow = "#c2c270"
blue = "#7a99b8"
magenta = "#b87a99"
cyan = "#7ab8b8"
white = "#eedfb4"

[colors.bright]
black = "#525252"
red = "#b87a7a"
green = "#7ab88a"
yellow = "#c2c270"
blue = "#7a99b8"
magenta = "#b87a99"
cyan = "#7ab8b8"
white = "#eedfb4"

[colors.dim]
black = "#525252"
red = "#b87a7a"
green = "#7ab88a"
yellow = "#c2c270"
blue = "#7a99b8"
magenta = "#b87a99"
cyan = "#7ab8b8"
white = "#eedfb4"