[colors.primary]
background = "#3A333C"
foreground = "#E0D9C4"
dim_foreground = "#BDBAB2"
bright_foreground = "#E0D9C4"

[colors.cursor]
text = "#3A333C"
cursor = "#E0D9C4"

[colors.vi_mode_cursor]
text = "#3A333C"
cursor = "#E0D9C4"

[colors.search.matches]
foreground = "#3A333C"
background = "#8F8A7B"

[colors.search.focused_match]
foreground = "#3A333C"
background = "#8AC271"

[colors.footer_bar]
foreground = "#3A333C"
background = "#8F8A7B"

[colors.hints.start]
foreground = "#3A333C"
background = "#C2B071"

[colors.hints.end]
foreground = "#3A333C"
background = "#8F8A7B"

[colors.selection]
text = "#3A333C"
background = "#746F62"

[colors.normal]
black = "#554A58"
red = "#C27171"
green = "#8AC271"
yellow = "#C2B071"
blue = "#719EC2"
magenta = "#C271AE"
cyan = "#71C2C2"
white = "#E0D9C4"

[colors.bright]
black = "#554A58"
red = "#C27171"
green = "#8AC271"
yellow = "#C2B071"
blue = "#719EC2"
magenta = "#C271AE"
cyan = "#71C2C2"
white = "#E0D9C4"

[colors.dim]
black = "#554A58"
red = "#C27171"
green = "#8AC271"
yellow = "#C2B071"
blue = "#719EC2"
magenta = "#C271AE"
cyan = "#71C2C2"
white = "#E0D9C4"