[colors.primary]
background = "#333333"
foreground = "#e9e9e2"
dim_foreground = "#bcbda8"
bright_foreground = "#e9e9e2"

[colors.cursor]
text = "#333333"
cursor = "#e9e9e2"

[colors.vi_mode_cursor]
text = "#333333"
cursor = "#e9e9e2"

[colors.search.matches]
foreground = "#333333"
background = "#8f916e"

[colors.search.focused_match]
foreground = "#333333"
background = "#7ab88a"

[colors.footer_bar]
foreground = "#333333"
background = "#8f916e"

[colors.hints.start]
foreground = "#333333"
background = "#c2c270"

[colors.hints.end]
foreground = "#333333"
background = "#8f916e"

[colors.selection]
text = "#333333"
background = "#727458"

[colors.normal]
black = "#4d4d4d"
red = "#b87a7a"
green = "#7ab88a"
yellow = "#c2c270"
blue = "#7a99b8"
magenta = "#b87a99"
cyan = "#7ab8b8"
white = "#e9e9e2"

[colors.bright]
black = "#4d4d4d"
red = "#b87a7a"
green = "#7ab88a"
yellow = "#c2c270"
blue = "#7a99b8"
magenta = "#b87a99"
cyan = "#7ab8b8"
white = "#e9e9e2"

[colors.dim]
black = "#4d4d4d"
red = "#b87a7a"
green = "#7ab88a"
yellow = "#c2c270"
blue = "#7a99b8"
magenta = "#b87a99"
cyan = "#7ab8b8"
white = "#e9e9e2"