[colors.primary]
background = "#CDD2E4"
foreground = "#20292B"
dim_foreground = "#4B6066"
bright_foreground = "#20292B"

[colors.cursor]
text = "#CDD2E4"
cursor = "#20292B"

[colors.vi_mode_cursor]
text = "#CDD2E4"
cursor = "#20292B"

[colors.search.matches]
foreground = "#CDD2E4"
background = "#7B959D"

[colors.search.focused_match]
foreground = "#CDD2E4"
background = "#852C42"

[colors.footer_bar]
foreground = "#CDD2E4"
background = "#7B959D"

[colors.hints.start]
foreground = "#CDD2E4"
background = "#85422C"

[colors.hints.end]
foreground = "#CDD2E4"
background = "#7B959D"

[colors.selection]
text = "#CDD2E4"
background = "#617B83"

[colors.normal]
black = "#ACB4D2"
red = "#2C5985"
green = "#852C42"
yellow = "#85422C"
blue = "#856F2C"
magenta = "#2C8585"
cyan = "#2C8559"
white = "#20292B"

[colors.bright]
black = "#ACB4D2"
red = "#2C5985"
green = "#852C42"
yellow = "#85422C"
blue = "#856F2C"
magenta = "#2C8585"
cyan = "#2C8559"
white = "#20292B"

[colors.dim]
black = "#ACB4D2"
red = "#2C5985"
green = "#852C42"
yellow = "#85422C"
blue = "#856F2C"
magenta = "#2C8585"
cyan = "#2C8559"
white = "#20292B"