[colors.primary]
background = "#2F3341"
foreground = "#B3E0EE"
dim_foreground = "#AABEC4"
bright_foreground = "#B3E0EE"

[colors.cursor]
text = "#2F3341"
cursor = "#B3E0EE"

[colors.vi_mode_cursor]
text = "#2F3341"
cursor = "#B3E0EE"

[colors.search.matches]
foreground = "#2F3341"
background = "#6E909A"

[colors.search.focused_match]
foreground = "#2F3341"
background = "#D88C9F"

[colors.footer_bar]
foreground = "#2F3341"
background = "#6E909A"

[colors.hints.start]
foreground = "#2F3341"
background = "#D89F8C"

[colors.hints.end]
foreground = "#2F3341"
background = "#6E909A"

[colors.selection]
text = "#2F3341"
background = "#57757E"

[colors.normal]
black = "#444A5E"
red = "#8CB2D8"
green = "#D88C9F"
yellow = "#D89F8C"
blue = "#D8C58C"
magenta = "#8CD8D8"
cyan = "#8CD8B2"
white = "#B3E0EE"

[colors.bright]
black = "#444A5E"
red = "#8CB2D8"
green = "#D88C9F"
yellow = "#D89F8C"
blue = "#D8C58C"
magenta = "#8CD8D8"
cyan = "#8CD8B2"
white = "#B3E0EE"

[colors.dim]
black = "#444A5E"
red = "#8CB2D8"
green = "#D88C9F"
yellow = "#D89F8C"
blue = "#D8C58C"
magenta = "#8CD8D8"
cyan = "#8CD8B2"
white = "#B3E0EE"