[colors.primary]
background = "#2F3C41"
foreground = "#EEB3B3"
dim_foreground = "#C4AAAA"
bright_foreground = "#EEB3B3"

[colors.cursor]
text = "#2F3C41"
cursor = "#EEB3B3"

[colors.vi_mode_cursor]
text = "#2F3C41"
cursor = "#EEB3B3"

[colors.search.matches]
foreground = "#2F3C41"
background = "#8F9A6E"

[colors.search.focused_match]
foreground = "#2F3C41"
background = "#9FD88C"

[colors.footer_bar]
foreground = "#2F3C41"
background = "#8F9A6E"

[colors.hints.start]
foreground = "#2F3C41"
background = "#8CD89F"

[colors.hints.end]
foreground = "#2F3C41"
background = "#8F9A6E"

[colors.selection]
text = "#2F3C41"
background = "#747E57"

[colors.normal]
black = "#44575E"
red = "#D88CB2"
green = "#9FD88C"
yellow = "#8CD89F"
blue = "#C5D88C"
magenta = "#D88C8C"
cyan = "#D8B38C"
white = "#EEB3B3"

[colors.bright]
black = "#44575E"
red = "#D88CB2"
green = "#9FD88C"
yellow = "#8CD89F"
blue = "#C5D88C"
magenta = "#D88C8C"
cyan = "#D8B38C"
white = "#EEB3B3"

[colors.dim]
black = "#44575E"
red = "#D88CB2"
green = "#9FD88C"
yellow = "#8CD89F"
blue = "#C5D88C"
magenta = "#D88C8C"
cyan = "#D8B38C"
white = "#EEB3B3"