[colors.primary]
background = "#412F2F"
foreground = "#EEDEB3"
dim_foreground = "#C4BDAA"
bright_foreground = "#EEDEB3"

[colors.cursor]
text = "#412F2F"
cursor = "#EEDEB3"

[colors.vi_mode_cursor]
text = "#412F2F"
cursor = "#EEDEB3"

[colors.search.matches]
foreground = "#412F2F"
background = "#9A6E84"

[colors.search.focused_match]
foreground = "#412F2F"
background = "#D89F8C"

[colors.footer_bar]
foreground = "#412F2F"
background = "#9A6E84"

[colors.hints.start]
foreground = "#412F2F"
background = "#D88C9F"

[colors.hints.end]
foreground = "#412F2F"
background = "#9A6E84"

[colors.selection]
text = "#412F2F"
background = "#7E576B"

[colors.normal]
black = "#5E4444"
red = "#8C9FD8"
green = "#D89F8C"
yellow = "#D88C9F"
blue = "#D88CC5"
magenta = "#9F8CD8"
cyan = "#C58CD8"
white = "#EEDEB3"

[colors.bright]
black = "#5E4444"
red = "#8C9FD8"
green = "#D89F8C"
yellow = "#D88C9F"
blue = "#D88CC5"
magenta = "#9F8CD8"
cyan = "#C58CD8"
white = "#EEDEB3"

[colors.dim]
black = "#5E4444"
red = "#8C9FD8"
green = "#D89F8C"
yellow = "#D88C9F"
blue = "#D88CC5"
magenta = "#9F8CD8"
cyan = "#C58CD8"
white = "#EEDEB3"