[colors.primary]
background = "#E4CDCD"
foreground = "#202B20"
dim_foreground = "#4B664B"
bright_foreground = "#202B20"

[colors.cursor]
text = "#E4CDCD"
cursor = "#202B20"

[colors.vi_mode_cursor]
text = "#E4CDCD"
cursor = "#202B20"

[colors.search.matches]
foreground = "#E4CDCD"
background = "#959D7B"

[colors.search.focused_match]
foreground = "#E4CDCD"
background = "#6F852C"

[colors.footer_bar]
foreground = "#E4CDCD"
background = "#959D7B"

[colors.hints.start]
foreground = "#E4CDCD"
background = "#43852C"

[colors.hints.end]
foreground = "#E4CDCD"
background = "#959D7B"

[colors.selection]
text = "#E4CDCD"
background = "#7B8361"

[colors.normal]
black = "#D2ACAC"
red = "#852C6F"
green = "#6F852C"
yellow = "#43852C"
blue = "#2C8543"
magenta = "#852C43"
cyan = "#85432C"
white = "#202B20"

[colors.bright]
black = "#D2ACAC"
red = "#852C6F"
green = "#6F852C"
yellow = "#43852C"
blue = "#2C8543"
magenta = "#852C43"
cyan = "#85432C"
white = "#202B20"

[colors.dim]
black = "#D2ACAC"
red = "#852C6F"
green = "#6F852C"
yellow = "#43852C"
blue = "#2C8543"
magenta = "#852C43"
cyan = "#85432C"
white = "#202B20"