[colors.primary]
background = "#E4D9CD"
foreground = "#2B2420"
dim_foreground = "#66534B"
bright_foreground = "#2B2420"

[colors.cursor]
text = "#E4D9CD"
cursor = "#2B2420"

[colors.vi_mode_cursor]
text = "#E4D9CD"
cursor = "#2B2420"

[colors.search.matches]
foreground = "#E4D9CD"
background = "#9D847B"

[colors.search.focused_match]
foreground = "#E4D9CD"
background = "#855A2C"

[colors.footer_bar]
foreground = "#E4D9CD"
background = "#9D847B"

[colors.hints.start]
foreground = "#E4D9CD"
background = "#85422C"

[colors.hints.end]
foreground = "#E4D9CD"
background = "#9D847B"

[colors.selection]
text = "#E4D9CD"
background = "#836A61"

[colors.normal]
black = "#D2BFAC"
red = "#2C4285"
green = "#855A2C"
yellow = "#85422C"
blue = "#856F2C"
magenta = "#2C6F85"
cyan = "#2C8558"
white = "#2B2420"

[colors.bright]
black = "#D2BFAC"
red = "#2C4285"
green = "#855A2C"
yellow = "#85422C"
blue = "#856F2C"
magenta = "#2C6F85"
cyan = "#2C8558"
white = "#2B2420"

[colors.dim]
black = "#D2BFAC"
red = "#2C4285"
green = "#855A2C"
yellow = "#85422C"
blue = "#856F2C"
magenta = "#2C6F85"
cyan = "#2C8558"
white = "#2B2420"