[colors.primary]
background = "#2F4138"
foreground = "#B8EEB3"
dim_foreground = "#ADC4AA"
bright_foreground = "#B8EEB3"

[colors.cursor]
text = "#2F4138"
cursor = "#B8EEB3"

[colors.vi_mode_cursor]
text = "#2F4138"
cursor = "#B8EEB3"

[colors.search.matches]
foreground = "#2F4138"
background = "#739A6E"

[colors.search.focused_match]
foreground = "#2F4138"
background = "#8CD88C"

[colors.footer_bar]
foreground = "#2F4138"
background = "#739A6E"

[colors.hints.start]
foreground = "#2F4138"
background = "#8CD8C5"

[colors.hints.end]
foreground = "#2F4138"
background = "#739A6E"

[colors.selection]
text = "#2F4138"
background = "#5B7E57"

[colors.normal]
black = "#445E53"
red = "#D88C9F"
green = "#8CD88C"
yellow = "#8CD8C5"
blue = "#C5D88C"
magenta = "#D88CC5"
cyan = "#C58CD8"
white = "#B8EEB3"

[colors.bright]
black = "#445E53"
red = "#D88C9F"
green = "#8CD88C"
yellow = "#8CD8C5"
blue = "#C5D88C"
magenta = "#D88CC5"
cyan = "#C58CD8"
white = "#B8EEB3"

[colors.dim]
black = "#445E53"
red = "#D88C9F"
green = "#8CD88C"
yellow = "#8CD8C5"
blue = "#C5D88C"
magenta = "#D88CC5"
cyan = "#C58CD8"
white = "#B8EEB3"