[colors.primary]
background = "#CFE4CD"
foreground = "#202B26"
dim_foreground = "#4B6659"
bright_foreground = "#202B26"

[colors.cursor]
text = "#CFE4CD"
cursor = "#202B26"

[colors.vi_mode_cursor]
text = "#CFE4CD"
cursor = "#202B26"

[colors.search.matches]
foreground = "#CFE4CD"
background = "#7B9D8C"

[colors.search.focused_match]
foreground = "#CFE4CD"
background = "#2C852C"

[colors.footer_bar]
foreground = "#CFE4CD"
background = "#7B9D8C"

[colors.hints.start]
foreground = "#CFE4CD"
background = "#2C856F"

[colors.hints.end]
foreground = "#CFE4CD"
background = "#7B9D8C"

[colors.selection]
text = "#CFE4CD"
background = "#618372"

[colors.normal]
black = "#AFD2AC"
red = "#852C42"
green = "#2C852C"
yellow = "#2C856F"
blue = "#6F852C"
magenta = "#852C6F"
cyan = "#6F2C85"
white = "#202B26"

[colors.bright]
black = "#AFD2AC"
red = "#852C42"
green = "#2C852C"
yellow = "#2C856F"
blue = "#6F852C"
magenta = "#852C6F"
cyan = "#6F2C85"
white = "#202B26"

[colors.dim]
black = "#AFD2AC"
red = "#852C42"
green = "#2C852C"
yellow = "#2C856F"
blue = "#6F852C"
magenta = "#852C6F"
cyan = "#6F2C85"
white = "#202B26"