[colors.primary]
background = "#412F2F"
foreground = "#EED1B3"
dim_foreground = "#C4B8AA"
bright_foreground = "#EED1B3"

[colors.cursor]
text = "#412F2F"
cursor = "#EED1B3"

[colors.vi_mode_cursor]
text = "#412F2F"
cursor = "#EED1B3"

[colors.search.matches]
foreground = "#412F2F"
background = "#9A856E"

[colors.search.focused_match]
foreground = "#412F2F"
background = "#D8B38C"

[colors.footer_bar]
foreground = "#412F2F"
background = "#9A856E"

[colors.hints.start]
foreground = "#412F2F"
background = "#D89F8C"

[colors.hints.end]
foreground = "#412F2F"
background = "#9A856E"

[colors.selection]
text = "#412F2F"
background = "#7E6B57"

[colors.normal]
black = "#5E4444"
red = "#8C9FD8"
green = "#D8B38C"
yellow = "#D89F8C"
blue = "#D8C58C"
magenta = "#8CC5D8"
cyan = "#8CD8B2"
white = "#EED1B3"

[colors.bright]
black = "#5E4444"
red = "#8C9FD8"
green = "#D8B38C"
yellow = "#D89F8C"
blue = "#D8C58C"
magenta = "#8CC5D8"
cyan = "#8CD8B2"
white = "#EED1B3"

[colors.dim]
black = "#5E4444"
red = "#8C9FD8"
green = "#D8B38C"
yellow = "#D89F8C"
blue = "#D8C58C"
magenta = "#8CC5D8"
cyan = "#8CD8B2"
white = "#EED1B3"